language: cpp

before_install:
    - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
    - sudo add-apt-repository --yes ppa:canonical-qt5-edgers/qt5-beta2
    - sudo apt-get update -qq
    - sudo apt-get install -qq qt5-qmake qtbase5-dev qtdeclarative5-dev libqt5svg5-dev qtmultimedia5-dev libqt5webkit5-dev libsqlite3-dev mesa-common-dev libglu1-mesa-dev
script:
    - qmake -qt=qt5 -v
    - qmake -qt=qt5 wint-im.pro
    - make
